# **Laboratorio 9:** Introducción a TensorFlow
**Programa:** [Bootcamp en Visión Artificial para los ODS](https://github.com/EdwinTSalcedo/Bootcamp-Computer-Vision-for-the-SDGs) - **Autor:** [Edwin Salcedo](https://github.com/EdwinTSalcedo)

¡Bienvenidos! Desde este laboratorio, nos enfocaremos en modelar arquitecturas de Deep Learning para tareas de Visión Artificial. La herramienta que usaremos es [Tensorflow](https://www.tensorflow.org/), la cual es una librería de código abierto para desarrollar pipelines de adquisición y procesamiento de datos, implementar modelos predictivos, y desplegar modelos para inferencia. Este framework fue lanzado en el 2015 por Google Brain; sin embargo, el 2019, Google lanzo TensorFlow 2.0 con funcionalidades actualizadas, un ecosistema mas compatible, y una mejor API de Keras.

Las estructura de datos principal en TensorFlow es el *tensor* y puedes pensar en este como estructuras de datos similares a los arrays de Numpy, por lo que TensorFlow en muchos sentidos comparte características y funcionalidades con esta librería. Después de todo, los arrays multidimensionales en Numpy son también tensores. Una de las principales ventajas de Tensorflow es que los modelos desarrollados con este framework tienen posibilidad de acloparse a infinidad de lenguajes de programación, dispositivos móviles y dispositivos embebidos.

<center><img src='https://media.giphy.com/media/QyJTDR8VkUtyKHNPm9/giphy.gif' width='30%'></center>

Registra los datos de tu equipo en esta sección al finalizar el laboratorio. 

**Nombre de equipo:**

**Miembros de equipo:**
- << nombre >> << apellido >> (Contribución sobre el 25%)
- << nombre >> << apellido >> (Contribución sobre el 25%)
- << nombre >> << apellido >> (Contribución sobre el 25%)
- << nombre >> << apellido >> (Contribución sobre el 25%) 


## 1. Tensores en TensorFlow

Como vimos anteriormente, los cálculos en redes neuronales son solo un conjunto de operaciones de álgebra lineal usando *tensores*, como una generalización de las matrices. La estructura de datos fundamental para las redes neuronales son los tensores y TF (así como casi todos los demás frameworks de aprendizaje profundo) están orientados a usar estas estructuras de datos. Puedes entender que un vector es un tensor unidimensional, una matriz es un tensor bidimensional, y una matriz con elementos de tres índices es un tensor tridimensional. Un tensor puede guardar información de cualquier archivo o conjunto de datos que haya sido convertido a valores numéricos. Por ejemplo, un tensor podría contener valores numéricos de los precios de casas, una imagen, o todas las palabras de un libro. 

<center>
<img src='https://drive.google.com/uc?id=1chsNh-3TlvxsLzHUE59aZ8XpAiHunZri' width='60%'>
</center>

La principal diferencia entre los tensores y las matrices NumPy es que los tensores se pueden usar en GPUs ([Graphical Processing Units](https://en.wikipedia.org/wiki/Graphics_processing_unit)) y TPUs ([Tensor Processing Units](https://en.wikipedia.org/wiki/Tensor_Processing_Unit)). El beneficio de ejecutar operaciones con tensores en la GPU/TPU y no en la CPU es la rapidez de los calculos, lo que significa que, si quisiéramos encontrar patrones en las representaciones numéricas de nuestros datos, las podremos encontrar en la mitad (o menos) del tiempo que tomaría encontrarlos usando CPUs ([Central Processing Units](https://en.wikipedia.org/wiki/Central_processing_unit)). Aunque tanto las las GPUs como las TPUs son caras y poco accesibles, Colab nos permite acceder a hardware con GPUs y TPUs de forma libre y con muchas opciones para entrenar modelos. 

Con los conceptos básicos cubiertos, es hora de explorar cómo podemos usar TF para trabajar con tensores. Primero iniciaremos importando TensorFlow. 

In [ ]:
# Importar Tensorflow y mostrar su versión
import tensorflow as tf

print('TensorFlow version:', tf.__version__)

TensorFlow version: 2.8.2


En general, uno no crea tensores por si mismo sino que programa a TF para crearlos. Esto debido a que TF tiene módulos integrados (como `tf.io` y tf.data) que pueden leer datasets y convertirlos automáticamente en tensores, para que después los modelos de redes neuronales los procesen por nosotros. Sin embargo, es muy importante entender como trabajar con ellos y comprender como funcionan. 

## 2. Creación de Tensores

Seis de las formas mas frecuentes para crear tensores se realizan con las funciones `tf.constant()`, `tf.Variable()`, `tf.fill()`, `tf.ones()`, `tf.zeros()` y `tf.random`. Las dos primeras permiten crear tensores con dimensión y valores variables; sin embargo, ambas se diferencian en que `tf.constant()` no permite modificar el tensor después de la creación, mientras que `tf.variable()` si. Entonces, podemos considerar a `tf.constant()` como las variables constantes presentes en la mayoría de lenguajes de programación. 

Por otro lado `tf.fill()`, `tf.ones()` y `tf.zeros()` permiten crear tensores con un valor predeterminado para todos los elementos del tensor. Finalmente, `tf.random` permite crear tensores con valores aleatorios. En las siguientes celdas exploraremos estos metodos.

In [ ]:
# Crear un escalar (Tensor en la dimensión 0). Un tensor puede tener muchas 
# dimensiones y la dimensión 0 sera para crear un número escalar independiente. 
scalar = tf.constant(12)
# Mostrar tensor
print(scalar)
# Comprobar el número de dimensiones de un tensor (ndim significa número de dimensiones)
print("N. dimensiones: ", scalar.ndim)

tf.Tensor(12, shape=(), dtype=int32)
N. dimensiones:  0


In [ ]:
# Crear un vector (Tensor de 1 dimensión)
vector = tf.constant([12, 12])
print(vector)
print("N. dimensiones: ", vector.ndim)

tf.Tensor([12 12], shape=(2,), dtype=int32)
N. dimensiones:  1


In [ ]:
# Crear una matriz (Tensor de 2 dimensiónes)
matrix = tf.constant([[4.6, 2.7],
                      [7.9, 10.1]])
print(matrix)
print("N. dimensiones: ", matrix.ndim)

tf.Tensor(
[[ 4.6  2.7]
 [ 7.9 10.1]], shape=(2, 2), dtype=float32)
N. dimensiones:  2


Como puedes notar, TF crea tensores con un tipo de datos `int32` o `float32`. Esto se conoce como precisión de 32 bits, lo que significa que TF hara uso de 32 valores binarios para guardar cada elemento del tensor. Cuanto mayor sea el número de bits, más preciso será el número a guardarse en memoria. Además que mientras mayor sea el número de bits, más espacio requerirá un tensor para guardarse en su equipo. Esta vez reduciremos la precisión a 16 bits por elemento del tensor.

In [ ]:
# Crear otra matriz y definir el tipo de datos
another_matrix = tf.constant([[5.3, 7.5],
                              [3.1, 2.],
                              [8.54, 2.4]], dtype=tf.float16) # Especificar el tipo de dato con 'dtype'
print(another_matrix)
# Similar a Numpy, la propiedad dtype permite ver el tipo de dato de cada elemento en el tensor
print("Tipo de dato:", another_matrix.dtype)

tf.Tensor(
[[5.3  7.5 ]
 [3.1  2.  ]
 [8.54 2.4 ]], shape=(3, 2), dtype=float16)
Tipo de dato: <dtype: 'float16'>


In [ ]:
# ¡Finalmente, creemos un tensor de 3 dimensiones!
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
print(tensor)
print("N. dimensiones: ", tensor.ndim)

# Aprovecharemos este tensor para imprimir mas atributos del tensor
# Recuperar la forma del tensor
print("Forma del tensor:", tensor.shape)
# Recuperar el número de elementos en el tensor. Para esto usaremos la función 
# tf.size(); sin embargo, esta función devuelve un tensor con la dimensión 0
# por lo que sera necesario convertirlo a un array de Numpy para ver directamente su valor
print("Número de elementos en el tensor:", tf.size(tensor).numpy()) # .numpy() convierte el tensor a un array de NumPy

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]], shape=(3, 2, 3), dtype=int32)
N. dimensiones:  3
Forma del tensor: (3, 2, 3)
Número de elementos en el tensor: 18


La diferencia entre `tf.variable()` y `tf.constant()` es que los tensores creados con `tf.constant()` son inmutables (no se pueden cambiar después de su definición), mientras que los tensores creados con `tf.variable()` son mutables (se pueden cambiar). Los ejemplos, planteados arriba son aplicables también a los tensores creados con `tf.variable()`. Desde este punto, nos concentraremos en los tensores variables. 

In [ ]:
# Veamos la estructura creada para ambos tipos de tensor con los mismos datos
variable_tensor = tf.Variable([10, 7])
constant_tensor = tf.constant([10, 7])
variable_tensor, constant_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# Cambiar el valor de un tensor
variable_tensor[0].assign(7)
variable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

La anterior operación generaría errores si la ejecutaramos con `constant_tensor`. Para definir que tipo de tensor usar, sera importante identificar si el tensor sera modificado en algún punto del programa, en ese caso siempre se sugiere usar `tf.Variable()`. Por otra parte, la siguiente celda muestra algunas maneras para iterar en tensores de TF. 

In [ ]:
for i in tensor:
  for j in i:
    for k in j:
      print("Iterate tensor:",k)
  print("\n")

Iterate tensor: tf.Tensor(1, shape=(), dtype=int32)
Iterate tensor: tf.Tensor(2, shape=(), dtype=int32)
Iterate tensor: tf.Tensor(3, shape=(), dtype=int32)
Iterate tensor: tf.Tensor(4, shape=(), dtype=int32)
Iterate tensor: tf.Tensor(5, shape=(), dtype=int32)
Iterate tensor: tf.Tensor(6, shape=(), dtype=int32)


Iterate tensor: tf.Tensor(7, shape=(), dtype=int32)
Iterate tensor: tf.Tensor(8, shape=(), dtype=int32)
Iterate tensor: tf.Tensor(9, shape=(), dtype=int32)
Iterate tensor: tf.Tensor(10, shape=(), dtype=int32)
Iterate tensor: tf.Tensor(11, shape=(), dtype=int32)
Iterate tensor: tf.Tensor(12, shape=(), dtype=int32)


Iterate tensor: tf.Tensor(13, shape=(), dtype=int32)
Iterate tensor: tf.Tensor(14, shape=(), dtype=int32)
Iterate tensor: tf.Tensor(15, shape=(), dtype=int32)
Iterate tensor: tf.Tensor(16, shape=(), dtype=int32)
Iterate tensor: tf.Tensor(17, shape=(), dtype=int32)
Iterate tensor: tf.Tensor(18, shape=(), dtype=int32)




Continuemos viendo ejemplos para tensores con valores iguales para todos los elementos.  

In [ ]:
# Crear un tensor con todos valores iguales a uno
ones_tensor = tf.ones(shape=(3, 2))
ones_tensor

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [ ]:
# Crear un tensor con todos valores iguales a cero
zeros_tensor = tf.zeros(shape=(2, 3))
zeros_tensor

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [ ]:
# Crear un tensor con todos valores iguales a un valor definido
value_tensor = tf.fill((3, 3), 7) # Este metodo requiere no definir nombres de parametro
value_tensor

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]], dtype=int32)>

Finalmente, podemos crear tensores con valores aleatorios, lo cual es bastante util cuando queremos simular un subconjunto de datos. Por ejemplo, imaginemos que tenemos un conjunto de imágenes en un tensor con el shape (32, 224, 224, 3), donde:

* 32 es el tamaño del batch (la cantidad de imágenes que ve una red neuronal en un momento dado).
* 224, 224 (las 2 primeras dimensiones) son el alto y el ancho de las imágenes en píxeles.
* 3 es el número de canales de color de la imagen (rojo, verde azul).

Podemos simular este caso usando la clase `tf.random.Generator`.

In [ ]:
# Crear un tensor aleatorio con la distribución de probabilidades uniforme 
# También podríamos usar random_batch.normal() en el caso de requerir una distribución normal
random_batch = tf.random.Generator.from_seed(42) # Establecer la semilla para la reproducibilidad
batch = random_batch.uniform(minval=0, maxval=255, shape=(32, 224, 224, 3),  dtype=tf.int32) # create tensor from a normal distribution 
batch

<tf.Tensor: shape=(32, 224, 224, 3), dtype=int32, numpy=
array([[[[243,  42, 111],
         [ 48,  81,  66],
         [181, 207, 217],
         ...,
         [ 31, 141, 144],
         [ 80, 161,  96],
         [  4, 130, 124]],

        [[ 61, 139,  86],
         [120,  30, 245],
         [107, 176, 156],
         ...,
         [ 20, 241,  13],
         [161, 215,  26],
         [147,  61,  88]],

        [[ 28,  32,  98],
         [ 41, 207,  56],
         [203, 236, 168],
         ...,
         [ 83,  75, 112],
         [237, 251, 227],
         [224, 119, 108]],

        ...,

        [[215,  11, 182],
         [120,  91, 171],
         [  6,  93,  80],
         ...,
         [143,   7, 243],
         [ 28, 202, 193],
         [ 60, 214,  97]],

        [[ 59, 211,  40],
         [254,  56,  57],
         [149, 214,  24],
         ...,
         [  2,  83, 169],
         [231,  80, 115],
         [ 86,  96, 194]],

        [[151,   5, 208],
         [ 20, 156, 229],
         [137, 19

Para concluir esta sección, veremos que también podemos crear tensores desde arrays de Numpy. Dos principales maneras de hacer esto es pasando un array de Numpy a la función `tf.constant()` o `tf.Variable()`, y convirtiendo un array de Numpy con `tf.convert_to_tensor(array_numpy)`.

In [ ]:
import numpy as np

# Crear una matriz NumPy entre 1 y 25
numpy_A = np.arange(1, 25, dtype=np.int32) 

A = tf.constant(numpy_A,  
                shape=[2, 4, 3]) # nota: el numero total de elementos de la forma (2*4*3) tiene que coincidir con el número de elementos en la matriz numpy_A
print("Array Numpy")
print(numpy_A)
print(type(numpy_A)) 
print("\n")
print("Tensor TF")
print(A)
print(type(A))

Array Numpy
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
<class 'numpy.ndarray'>


Tensor TF
tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]], shape=(2, 4, 3), dtype=int32)
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [ ]:
print("Retorno a Array Numpy")
back_numpy = A.numpy()

print(back_numpy)
print(type(back_numpy))

Retorno a Array Numpy
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]]
<class 'numpy.ndarray'>


## 3. Operaciones con Tensores

### 3.1 Operaciones básicas
Las operaciones básicas como la suma, resta, multiplicación y división entre un tensor y un valor escalar son aplicables directamente con signos respectivos. Por ejemplo:  

In [ ]:
# Agregar valores a un tensor usando el operador de suma
tensor = tf.Variable([[10, 7], [3, 4]])
tensor = tensor + 10
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

TF también tiene funciones para realizar las mismas operaciones de manera optimizada: `tf.multiply()`, `tf.add()`, `tf.substract()`, `tf.divide()`. Se sugiere priorizar el uso de estas funciones cada vez que se pueda. Estas funciones tienen la ventaja de ejecutarse de manera optimizada cuando se esta trabajando con modelos y estos forman parte de un [gráfico de TensorFlow](https://www.tensorflow.org/tensorboard/graphs).

In [ ]:
# Usar la función equivalente al operador '*' (multiplicar)
tensor = tf.multiply(tensor, 20)
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[400, 340],
       [260, 280]], dtype=int32)>

### 3.2 Multiplicación de Matrices

Una de las operaciones más comunes en los algoritmos de aprendizaje automático es la multiplicación de matrices. TensorFlow implementa esta operación con el método `tf.matmul()`. Las dos reglas principales para realizar la multiplicación de matrices (simbolizada por @) son: 

1. Las dimensiones internas de las matrices deben coincidir.
  - (3, 5) @ (3, 5) no funcionara 
  - (5, 3) @ (3, 5) funciona
  - (3, 5) @ (5, 3) funciona
2. La matriz resultante tiene la forma de las dimensiones exteriores.
  - (5, 3) @ (3, 5) -> (5, 5)
  - (3, 5) @ (5, 3) -> (3, 3)

In [ ]:
print(tensor)
tensor = tf.matmul(tensor, tensor)
print(tensor)

tf.Tensor(
[[400 340]
 [260 280]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[248400 231200]
 [176800 166800]], shape=(2, 2), dtype=int32)


In [ ]:
# Python también tiene un operador directo para realizar multiplicación de matrices: @ 
c = tf.Variable([[1.0, 2.0], [3.0, 4.0]])
d = tf.Variable([[1.0, 1.0], [0.0, 1.0]])
e = c @ d
print(e)

tf.Tensor(
[[1. 3.]
 [3. 7.]], shape=(2, 2), dtype=float32)


### 3.3 Cambiar la forma de tensores

Remodelar o *Reshape* tensores es una operación muy común. Primero verificamos el tamaño actual de un tensor con `tf.size()`. Luego, para remodelar un tensor, usamos una de las siguientes funciones: 
- `tf.reshape()` para remodelar un tensor a una forma objetivo.
- `tf.transpose()` para intercambiar las dimensiones de un tensor dado, también conocido como transponer.

In [ ]:
# Crea un tensor (3,2)
# Nota: Una practica usual es denominar a las matrices con una mayuscula y a los vectores con letras minusculas
X = tf.Variable([[1, 2],
                 [3, 4],
                 [5, 6]])

# Crear otro tensor (3, 2) 
Y = tf.Variable([[7, 8],
                 [9, 10],
                 [11, 12]])

# Multiplicar X y Y causara errores debido a que sus dimensiones internas no tienen el mismo valor
# Por esa razón, es necesario aplicar reshape
Z = tf.reshape(Y, shape=(2, 3))
result = tf.matmul(X, Z)
print(result)

# Intentemos con la función tf.transpose()
T = tf.transpose(Y)
result_transpose = tf.matmul(X, Z)
print(result_transpose)

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[ 7,  8],
       [ 9, 10],
       [11, 12]], dtype=int32)>
tf.Tensor(
[[ 27  30  33]
 [ 61  68  75]
 [ 95 106 117]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[ 27  30  33]
 [ 61  68  75]
 [ 95 106 117]], shape=(3, 3), dtype=int32)


### 3.4 El producto punto

Otra operación muy utilizada en redes neuronales es el [producto punto](https://es.wikipedia.org/wiki/Producto_escalar#:~:text=Algebraicamente%2C%20el%20producto%20punto%20es,coseno%20del%20%C3%A1ngulo%20entre%20ellos.), el cual es la suma de los productos de las correspondientes entradas en dos secuencias de números. Geométricamente, es el producto de dos magnitudes euclidianas de los dos vectores y el coseno del ángulo entre ellos. Esta operación se puede implementar con la funcion `tf.tensordot()` especificando el eje=2. 

In [ ]:
dotproduct = tf.tensordot(X, Z, axes = 2)
dotproduct

<tf.Tensor: shape=(), dtype=int32, numpy=217>

### 3.5 Exprimir un tensor (eliminar todas las dimensiones iguales a la unidad)

Un problema común al procesar conjuntos de datos es la carga de datasets y que la estructura de datos en la que se carguen tenga dimensiones con valor 1. Si necesita eliminar estas dimensiones  de un tensor, puede usar `tf.squeeze()`.

In [ ]:
# Crear un tensor en la quinta dimensión con 20 elementos entre el 0 y el 20
tensor = tf.Variable(initial_value=[[[[np.random.randint(0, 20, 20)]]]], shape=(1, 1, 1, 1, 20))
print(tensor.shape)
print(len(tensor.shape))

(1, 1, 1, 1, 20)
5


In [ ]:
# Exprimir el tensor (eliminar todas las dimensiones con valor 1)
tensor_squeezed = tf.squeeze(tensor)
print(tensor_squeezed.shape)

(20,)


## 4. Acceder a la GPU

Como se menciono anteriormente, acceder a la GPU trae muchos beneficios para el entrenamiento e inferencia de modelos. Puedes comprobar si tienes acceso a la GPU en tu equipo local o en la nube usando la siguiente instrucción: 


In [ ]:
print(tf.config.list_physical_devices('GPU'))

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


Si la anterior celda genera una matriz vacía (o nada), significa que no tienes acceso a la GPU (o al menos que TensorFlow no se puede conectar). Colab dispone de GPU para todos los usuarios, por lo que deberías asegurarte que la GPU esta activada de esta manera:

> Seleccionando en la barra superior de funciones *Runtime -> Change Runtime Type -> Select GPU* 

Una vez que haya cambiado el Runtime Type, ejecute la anterior celda para verificar que el la GPU ya esta accesible. Un vez ya este activa, TF se asegurara de usarla siempre que se pueda. 

In [ ]:
import tensorflow as tf
print(tf.config.list_physical_devices('GPU'))

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


Finalmente, puedes acceder a mas información sobre la GPU usando la siguiente instrucción de consola.

In [ ]:
!nvidia-smi

Thu Jun  9 00:12:26 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   39C    P0    33W / 250W |    377MiB / 16280MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

##**Ejercicio 1:** Trabajando con Tensores

1. Crear tres tensores que contengan valores aleatorios entre 0 y 20 con forma [5, 300, 3], mostrar estos tensores y mostrar los elementos que se repiten en los tres.
2. Crear dos tensores con valores aleatorios entre 0 y 1 con forma [224, 224, 3], y encontrar su producto punto. 
3. Encuentrar los valores mínimo y máximo de los tensores que creó en el anterior punto.
4. Crear un tensor con valores aleatorios entre el 0 y 1 usando una la distribución uniforme y con la forma [1, 224, 224, 3]. Luego exprimirlo para cambiar a la forma a [224, 224, 3].
5. Crear 5 imágenes de 5x5 con Numpy y transformarlas en un tensor con las dimensiones [5,1,1,5,5]. 

## **Ejercicio 2:** Registro de asistencia
Este ejercicio requiere modelar el registro y contabilización de asistencias en una escuela usando tensores de TensorFlow. Puede inventar una lista de 15 estudiantes que participaron 60 días de clase durante un trimestre. Aunque no todos los estudiantes asistieron los 60 días, usted tiene el registro de cuando asistieron y cuando no. Su tarea sera contabilizar los siguientes puntos: 
- ¿Cual fue el estudiante que tuvo mas faltas?
- ¿Cuantas asistencias tiene cada estudiante?
- ¿Cual es el promedio de asistencia en el curso?
- ¿Que estudiante tuvo menos faltas? 

## 5. Referencias
- [Introducción a los tensores ](https://www.tensorflow.org/guide/tensor)
- [Variables en TensorFlow](https://www.tensorflow.org/guide/variable)
- [How to Create Tensors with Known Values?](https://www.dummies.com/article/technology/information-technology/ai/machine-learning/create-tensors-known-values-253479/) 
- [TensorFlow Basics](https://www.tensorflow.org/guide/basics)
- [Examinando el gráfico de TensorFlow](https://www.tensorflow.org/tensorboard/graphs) 